version: '3.7'

services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  node:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3333
    volumes:
      - ./:/app
    networks:
      - system
    command: pnpm dev

networks:
  system:
