version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres-seat-scheduler-api
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - system

networks:
  system:
    driver: bridge
