version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - system

  # node:
  #   build:
  #     context: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3333
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - system

networks:
  system:
    driver: bridge
